title: Open Coding 
description: "Class of 2027"
owner_name: Ruta Sirdeshmukh
github_username: ruta-sir 
github_repo: "student" 
baseurl: "/student" 
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/ruta-sir/student" }
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.md